set $mod Mod4
set $term foot

# Development-only nested session.
default_border pixel 2
focus_follows_mouse yes

bindsym $mod+Return exec $term
bindsym $mod+Shift+e exit

exec_always $term
exec_always /home/carladrianatan/myOS/MyOS/target/debug/myos-state-engine
exec_always /home/carladrianatan/myOS/MyOS/target/debug/myos-shell
